# Generated by Django 4.0.3 on 2022-04-14 00:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('user', 'post')},
        ),
    ]
